### ISSUE TITLE
About prepare_data.py

### ISSUE THREAD

**Issue by dongqian0206** [BorealisAI/cross_domain_coherence#1]
Hi Peng,

Thanks for your released code. 

I can not run prepare_data.py successfully. It seems a dataset problem (see the following output). Is it the same for your side? 

> OSError: Not a gzipped file

Best,

Dong Qian

**Comment by billy-inn** [comment]
The script works for me with no problem. From my experience, "OSError" may be caused by memory issue. Also, if the files are downloaded successfully by the script, you can try other tools to extract the files.

**Comment by dongqian0206** [comment]
> The script works for me with no problem. From my experience, "OSError" may be caused by memory issue. Also, if the files are downloaded successfully by the script, you can try other tools to extract the files.

Thanks.
